### ISSUE TITLE
Support PKCE Code Challenege

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/mockoidc#23]

**Comment by NickMeves** [comment]
@JoelSpeed - I think you mentioned you had a PR or 2 integrating this into a few of our provider unit tests?

This might be good to think about support for @braunsonm 's PR adding PKSE support specifically to OIDC providers.

**Comment by braunsonm** [comment]
PKCE*

I could look at adding this support. Could you point me to where oauth2-proxy tests run against this mockoidc server?

**Comment by JoelSpeed** [comment]
Yeah agreed, this would be good to get in. For now, in [this test](https://github.com/oauth2-proxy/oauth2-proxy/blob/d34644e16072329ebe78cef362dbc2bce59edf5e/pkg/providers/oidc/provider_test.go#L88-L106) I just wrote a middleware that returned a discovery document pretending to support to code algorithms, so we have a test, it's just not ideal, and if we want to do more thorough testing with this package, I think it would be good to have actual support within the mockoidc provider

**Comment by NickMeves** [comment]
I looked over the code to remind myself the architecture again (its been a while):

Looks like `session.go` is the ideal spot to store the challenge code & method. With the `Authorize` and `Token` calls under `handlers` being the spots to handle the 2 ends of the flow (assuming I'm remembering PKCE right).
